server:
  port: 9501
eureka:
  client:
    service-url:
      defaultZone: http://admin:js@eureka1:7001/eureka,http://admin:js@eureka2:7002/eureka
    register-with-eureka: false
spring:
  application:
    name: m-zuul-gateway